export MAKEFLAGS += --no-print-directory
PROJECT_NAME    := sygl_test
BUILD           := build
SOURCES         := src
ROM_TITLE       := SYGL TEST
ROM_CODE        := SYGL
include $(BUTANO_PATH)/butano.mak
